#!/bin/bash

# :( https://github.com/monero-project/monero/issues/1763
# TODO rewrite to proper foreground mode after it get solved

echo "* Starting node 1..."
/usr/bin/monerod --restricted-rpc --testnet --p2p-bind-port 28080 --rpc-bind-port 28081 --zmq-rpc-bind-port 28082 --no-igd --hide-my-port --data-dir /data/node-1 --p2p-bind-ip 127.0.0.1 --rpc-bind-ip 0.0.0.0 --log-level 0 --add-exclusive-node 127.0.0.1:38080 --start-mining 9wviCeWe2D8XS82k2ovp5EUYLzBt9pYNW2LXUFsZiv8S3Mt21FZ5qQaAroko1enzw3eGr9qC7X1D7Geoo2RrAotYPwq9Gm8 --confirm-external-bind --non-interactive

# s6-svc -d /var/run/s6/services/node-1
