version: '2.1'

services:
  database:
    image: "postgres"
  monero:
    build: docker/monero-test-net
  openpool:
    image: openpool
    depends_on:
      - database
      - monero
    build: .
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
    ports:
      - 31415:31415
      - 9229:9229
    command: ./wait-for-it.sh database:5432 -- node --inspect=0.0.0.0:9229 index.js --config docker-compose.ini
