version: '2.1'

services:
  database:
    image: postgres
  monero:
    build: docker/monero
  redis:
    image: redis
  openpool:
    image: openpool
    depends_on:
      - database
      - monero
    build:
      context: .
      dockerfile: docker/openpool/Dockerfile
    environment:
      NODE_ENV: development
      DEBUG: '*,-sequelize'
    volumes:
      - ./:/usr/src/app
    ports:
      - 9229:9229 # debugger
      - 1999:1999 # front-end
      - 3000:3000 # push notifications
      - 31415:31415 # miners
    command: ./tools/wait-for-it.sh database:5432 -- nodemon --watch index.js --watch manifest --watch src --ignore src/ui --inspect=0.0.0.0:9229 ./index.js -c docker/openpool/docker-compose.ini
  miner:
    build: docker/xmrig
    command: >
        --url=openpool:10001 
        --user=9wq792k9sxVZiLn66S3Qzv8QfmtcwkdXgM5cWGsXAPxoQeMQ79md51PLPCijvzk1iHbuHi91pws5B7iajTX9KTtJ4bh2tCh 
        --pass=x 
        --keepalive 
        --donate-level=1 
        --max-cpu-usage 25 
        --no-huge-pages 
        --threads=1 
        --print-time=5
