#!/bin/bash

echo "* Starting wallet RPC 2..."
/usr/bin/monero-wallet-rpc --rpc-bind-port 38082 --testnet --wallet-file /data/wallet-2/wallet.bin --rpc-bind-ip 0.0.0.0 --confirm-external-bind --rpc-login monerorpc:rpcpassword
