#!/bin/bash

echo "* Starting wallet RPC 1..."
/usr/bin/monero-wallet-rpc --rpc-bind-port 28083 --daemon-port 28081 --testnet --wallet-file /data/wallet-1/wallet.bin --rpc-bind-ip 0.0.0.0 --confirm-external-bind --rpc-login monerorpc:rpcpassword --password ""
