#!/bin/bash

echo "* Starting node 2..."
/usr/bin/monerod --restricted-rpc --testnet --p2p-bind-port 38080 --rpc-bind-port 38081 --zmq-rpc-bind-port 38082  --no-igd --hide-my-port --data-dir /data/node-2 --p2p-bind-ip 127.0.0.1 --rpc-bind-ip 0.0.0.0 --log-level 0 --add-exclusive-node 127.0.0.1:28080 --confirm-external-bind --non-interactive

# s6-svc -d /var/run/s6/services/node-2


