'use strict'

const BigNum = require('bignum')
const Crypto = require('crypto')
const CryptoNoteUtil = require('cryptonote-util')
const CryptoNight = require('node-cryptonight').async

const AbstractCoin = require('./abstract-coin')

const INSTANCE_ID = Crypto.randomBytes(4)

class Monero extends AbstractCoin {
  constructor (address, daemonRpc) {
    super()
    this.address = address // pool address
    this.daemon = daemonRpc
  }

  /**
   * @return {BigNum} the base difficulty
   */
  getBaseDifficulty () {
    return new BigNum('FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF', 16)
  }

  /**
   * Fetches the most recent block template form the monero daemon
   *
   * @returns {Promise.<BlockTemplate>} block template
   */
  _getBlockTemplate () {
    return this.daemon
      .request('getblocktemplate', { reserve_size: 17, wallet_address: this.address })
      .then(response => {
        if (response.error) {
          throw new Error(response.error.message)
        }
        return response.result
      })
      .then(blockTemplate => new BlockTemplate(blockTemplate))
  }

  /**
   * Submits a block to the Monero dameon
   *
   * @param {Block} block to be submitted to the daemon
   */
  submit (block) {
    return this.daemon
      .request('submitblock', [block.blob.toString('hex')])
      .then(response => {
        if (response.error) {
          throw new Error(response.error.message)
        }
        return response.result
      })
  }
}

class BlockTemplate {
  constructor (blockTemplate) {
    this._blockTemplate = blockTemplate

    this.height = blockTemplate.height
    this.difficulty = blockTemplate.difficulty
    this.reservedOffset = blockTemplate.reserved_offset
    this.previousHash = blockTemplate.previous_hash
    this.blockTemplateHex = blockTemplate.blocktemplate_blob
    this.blockHashingHex = blockTemplate.blockhashing_blob // unused
    Object.freeze(this)
  }

  /**
   * Generates a block hashing blob that will be submitted to the miner
   *
   * @param {Number} extra_nonce unique number per job
   * @returns {Buffer} block hashing blob
   */
  getBlockHashingBlob (extra_nonce) { // eslint-disable-line camelcase
    const blockTemplateBlob = Buffer.from(this.blockTemplateHex, 'hex')
    // Copy the instance identifier to the reserved offset + 4 bytes. Copy in 4 bytes.
    INSTANCE_ID.copy(blockTemplateBlob, this.reservedOffset + 4, 0, 3)
    blockTemplateBlob.writeUInt32BE(extra_nonce, this.reservedOffset)
    return CryptoNoteUtil.convert_blob(blockTemplateBlob)
  }

  /**
   * Generates a block blob that can be submitted to the monero daemon
   *
   * @param {Buffer} nonce generated by the mining process
   * @param {Number} extra_nonce generated by the pool before generating the block hashing blob
   * @returns {Promise.<Block>} block
   */
  getBlockBlob (nonce, extra_nonce) { // eslint-disable-line camelcase
    const blockTemplateBlob = Buffer.from(this.blockTemplateHex, 'hex')
    blockTemplateBlob.writeUInt32BE(extra_nonce, this.reservedOffset)
    // Copy the instance identifier to the reserved offset + 4 bytes. Copy in 4 bytes.
    INSTANCE_ID.copy(blockTemplateBlob, this.reservedOffset + 4, 0, 3)
    const blockBlob = CryptoNoteUtil.construct_block_blob(blockTemplateBlob, nonce)
    return Promise.resolve(new Block(blockBlob))
  }
}

class Block {
  constructor (blockBlob) {
    this._blockBlob = blockBlob
  }

  /**
   * The block
   *
   * @returns {Buffer} blob
   */
  get blob () {
    return this._blockBlob
  }

  /**
   * Returns the identifer of the block.
   * The identifier of a block is the result of hashing the following data with Keccak:
   *  * size of [ block_header, merkle root hash, and number of transactions ] in bytes
   *  * block_header
   *  * merkle root hash
   *  * number of transactions
   *
   * @returns {Number} identifier
   */
  get id () {
    return CryptoNoteUtil.get_block_id(this._blockBlob)
  }

  /**
   * Calculates the hash of the block
   *
   * @returns {Promise.<Buffer>} block hash
   */
  get hash () {
    const convertedBlob = CryptoNoteUtil.convert_blob(this._blockBlob)
    if (this._hash) {
      return this.hash
    }
    this.hash = new Promise((resolve, reject) => CryptoNight(convertedBlob, (hash) => resolve(hash)))
    return this.hash
  }

  /**
   * It validates that the block matches the given hash.
   * A succesful promise containing the block is returned in that case.
   * Otherwise the promise is rejected
   *
   * @param {Buffer} hash hash to compare to
   * @returns {Promise.<Block>} block
   */
  checkHashMatches (hash) {
    return this.hash.then(h => h.equals(hash)
      ? this
      : Promise.reject(new Error('Invalid hash'))
    )
  }
}

module.exports = Monero
